<?php
namespace dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

class Group {

    private $gId; // Object q(g_id)
    private $gName; // Object q(g_name)
    private $tasksCount; // Object q(tasks_count)

    /**
     * @return Object
     */
    public function getGId() {
        return $this->gId;
    }

    /**
     * @param Object $value
     */
    public function setGId($value) {
        $this->gId = $value;
    }

    /**
     * @return Object
     */
    public function getGName() {
        return $this->gName;
    }

    /**
     * @param Object $value
     */
    public function setGName($value) {
        $this->gName = $value;
    }

    /**
     * @return Object
     */
    public function getTasksCount() {
        return $this->tasksCount;
    }

    /**
     * @param Object $value
     */
    public function setTasksCount($value) {
        $this->tasksCount = $value;
    }
}