<?php

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net


include_once __DIR__ . '/Group.php';
include_once __DIR__ . '/GroupEx.php';

class GroupsDao
{
    /**
     * @var \DataStore
     */
    protected $ds;

    public function __construct($ds)
    {
        $this->ds = $ds;
    }

    /**
     * (C)RUD: groups
     * Generated/AI values are passed to $p param
     * @param Group $p
     * @return void
     * @throws \Exception
     */
    public function create_group($p)
    {
        $sql = "insert into groups (g_name) values (?)";
        $ai_values = array("g_id" => null);
        $res = $this->ds->insert($sql, array($p->get_g_name()), $ai_values);
        $p->set_g_id($ai_values["g_id"]);
        return $res;
    }

    /**
     * C(R)UD: groups
     * @return Group[]
     * @throws \Exception
     */
    public function read_group_list()    {
        $sql = "select * from groups";
        $res = array();
        $_map_cb = function ($row) use (&$res) {
            $obj = new Group();
            $obj->set_g_id($row["g_id"]); // t <- t
            $obj->set_g_name($row["g_name"]); // t <- t
            array_push($res, $obj);
        };
        $this->ds->queryRowList($sql, array(), $_map_cb);
        return $res;
    }

    /**
     * C(R)UD: groups
     * @param int $g_id
     * @return Group|FALSE on failure
     * @throws \Exception
     */
    public function read_group($g_id)
    {
        $sql = "select * from groups where g_id=?";
        $row = $this->ds->queryRow($sql, array($g_id));
        if ($row) {
            $obj = new Group();
            $obj->set_g_id($row["g_id"]); // t <- t
            $obj->set_g_name($row["g_name"]); // t <- t
            return $obj;
        }
        return FALSE;
    }

    /**
     * CR(U)D: groups
     * @param Group $p
     * @throws \Exception
     */
    public function update_group($p)
    {
        $sql = "update groups set g_name=? where g_id=?";
        return $this->ds->execDML($sql, array($p->get_g_name(), $p->get_g_id()));
    }

    /**
     * CRU(D): groups
     * @param int $g_id
     * @throws \Exception
     */
    public function delete_group($g_id)
    {
        $sql = "delete from groups where g_id=?";
        return $this->ds->execDML($sql, array($g_id));
    }

    /**
     * @return GroupEx[]
     * @throws \Exception
     */
    public function get_groups()    {
        $sql = "select g.*, "
            . "\n (select count(*) from tasks where g_id=g.g_id) as tasks_count"
            . "\n from groups g";
        $res = array();
        $_map_cb = function ($row) use (&$res) {
            $obj = new GroupEx();
            $obj->set_g_id($row["g_id"]); // q <- q
            $obj->set_g_name($row["g_name"]); // q <- q
            $obj->set_tasks_count($row["tasks_count"]); // q <- q
            array_push($res, $obj);
        };
        $this->ds->queryRowList($sql, array(), $_map_cb);
        return $res;
    }

    /**
     * @param string $g_id
     * @return int the affected rows count
     * @throws \Exception
     */
    public function delete_tasks($g_id)
    {
        $sql = "delete from tasks where g_id=?";
        return $this->ds->execDML($sql, array($g_id));
    }
}
