<?php

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

class ProjectEx
{
    /**
     * @var int
     */
    private $p_id;
    /**
     * @var string
     */
    private $p_name;
    /**
     * @var int
     */
    private $p_tasks_count;

    public function get_p_id(): int
    {
        return $this->p_id;
    }

    public function set_p_id(int $value)
    {
        $this->p_id = $value;
    }

    public function get_p_name(): string
    {
        return $this->p_name;
    }

    public function set_p_name(string $value)
    {
        $this->p_name = $value;
    }

    public function get_p_tasks_count(): int
    {
        return $this->p_tasks_count;
    }

    public function set_p_tasks_count(int $value)
    {
        $this->p_tasks_count = $value;
    }
}