<?php

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

class ProjectEx
{
    /**
     * @var object
     */
    private $p_id;
    /**
     * @var object
     */
    private $p_name;
    /**
     * @var object
     */
    private $p_tasks_count;
    /**
     * @var int
     */
    private $g_id;
    /**
     * @var string
     */
    private $g_name;
    /**
     * @var int
     */
    private $g_tasks_count;

    public function get_p_id()
    {
        return $this->p_id;
    }

    public function set_p_id($value)
    {
        $this->p_id = $value;
    }

    public function get_p_name()
    {
        return $this->p_name;
    }

    public function set_p_name($value)
    {
        $this->p_name = $value;
    }

    public function get_p_tasks_count()
    {
        return $this->p_tasks_count;
    }

    public function set_p_tasks_count($value)
    {
        $this->p_tasks_count = $value;
    }

    public function get_g_id(): int
    {
        return $this->g_id;
    }

    public function set_g_id(int $value)
    {
        $this->g_id = $value;
    }

    public function get_g_name(): string
    {
        return $this->g_name;
    }

    public function set_g_name(string $value)
    {
        $this->g_name = $value;
    }

    public function get_g_tasks_count(): int
    {
        return $this->g_tasks_count;
    }

    public function set_g_tasks_count(int $value)
    {
        $this->g_tasks_count = $value;
    }
}