<?php

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

class Task
{
    /**
     * @var Integer
     */
    private $tId;
    /**
     * @var Integer
     */
    private $gId;
    /**
     * @var Integer
     */
    private $tPriority;
    /**
     * @var String
     */
    private $tDate;
    /**
     * @var String
     */
    private $tSubject;
    /**
     * @var String
     */
    private $tComments;

    public function getTId()
    {
        return $this->tId;
    }

    public function setTId($value)
    {
        $this->tId = $value;
    }

    public function getGId()
    {
        return $this->gId;
    }

    public function setGId($value)
    {
        $this->gId = $value;
    }

    public function getTPriority()
    {
        return $this->tPriority;
    }

    public function setTPriority($value)
    {
        $this->tPriority = $value;
    }

    public function getTDate()
    {
        return $this->tDate;
    }

    public function setTDate($value)
    {
        $this->tDate = $value;
    }

    public function getTSubject()
    {
        return $this->tSubject;
    }

    public function setTSubject($value)
    {
        $this->tSubject = $value;
    }

    public function getTComments()
    {
        return $this->tComments;
    }

    public function setTComments($value)
    {
        $this->tComments = $value;
    }
}