<?php

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

class Task
{
    /**
     * @var int
     */
    private $tId;
    /**
     * @var int
     */
    private $gId;
    /**
     * @var int
     */
    private $tPriority;
    /**
     * @var string
     */
    private $tDate;
    /**
     * @var string
     */
    private $tSubject;
    /**
     * @var string
     */
    private $tComments;

    public function getTId(): int
    {
        return $this->tId;
    }

    public function setTId(int $value)
    {
        $this->tId = $value;
    }

    public function getGId(): int
    {
        return $this->gId;
    }

    public function setGId(int $value)
    {
        $this->gId = $value;
    }

    public function getTPriority(): int
    {
        return $this->tPriority;
    }

    public function setTPriority(int $value)
    {
        $this->tPriority = $value;
    }

    public function getTDate(): string
    {
        return $this->tDate;
    }

    public function setTDate(string $value)
    {
        $this->tDate = $value;
    }

    public function getTSubject(): string
    {
        return $this->tSubject;
    }

    public function setTSubject(string $value)
    {
        $this->tSubject = $value;
    }

    public function getTComments(): string
    {
        return $this->tComments;
    }

    public function setTComments(string $value)
    {
        $this->tComments = $value;
    }
}