<?php
namespace dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

class Task {

    private $tId; // Integer t(t_id)
    private $gId; // Integer t(g_id)
    private $tPriority; // Integer t(t_priority)
    private $tDate; // String t(t_date)
    private $tSubject; // String t(t_subject)
    private $tComments; // String t(t_comments)

    /**
     * @return Integer
     */
    public function getTId() {
        return $this->tId;
    }

    /**
     * @param Integer $value
     */
    public function setTId($value) {
        $this->tId = $value;
    }

    /**
     * @return Integer
     */
    public function getGId() {
        return $this->gId;
    }

    /**
     * @param Integer $value
     */
    public function setGId($value) {
        $this->gId = $value;
    }

    /**
     * @return Integer
     */
    public function getTPriority() {
        return $this->tPriority;
    }

    /**
     * @param Integer $value
     */
    public function setTPriority($value) {
        $this->tPriority = $value;
    }

    /**
     * @return String
     */
    public function getTDate() {
        return $this->tDate;
    }

    /**
     * @param String $value
     */
    public function setTDate($value) {
        $this->tDate = $value;
    }

    /**
     * @return String
     */
    public function getTSubject() {
        return $this->tSubject;
    }

    /**
     * @param String $value
     */
    public function setTSubject($value) {
        $this->tSubject = $value;
    }

    /**
     * @return String
     */
    public function getTComments() {
        return $this->tComments;
    }

    /**
     * @param String $value
     */
    public function setTComments($value) {
        $this->tComments = $value;
    }
}