<?php

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

class Project
{
    /**
     * @var int
     */
    private $p_id;
    /**
     * @var string
     */
    private $p_name;

    public function get_p_id(): int
    {
        return $this->p_id;
    }

    public function set_p_id(int $value)
    {
        $this->p_id = $value;
    }

    public function get_p_name(): string
    {
        return $this->p_name;
    }

    public function set_p_name(string $value)
    {
        $this->p_name = $value;
    }
}