<?php

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/


class Project
{
    /**
     * @var int
     */
    private $p_id;
    /**
     * @var string
     */
    private $p_name;

    public function get_p_id()
    {
        return $this->p_id;
    }

    public function set_p_id($value)
    {
        $this->p_id = $value;
    }

    public function get_p_name()
    {
        return $this->p_name;
    }

    public function set_p_name($value)
    {
        $this->p_name = $value;
    }
}
