<?php

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/


class Task
{
    /**
     * @var int
     */
    private $t_id;
    /**
     * @var int
     */
    private $p_id;
    /**
     * @var int
     */
    private $t_priority;
    /**
     * @var string
     */
    private $t_date;
    /**
     * @var string
     */
    private $t_subject;
    /**
     * @var string
     */
    private $t_comments;

    public function get_t_id()
    {
        return $this->t_id;
    }

    public function set_t_id($value)
    {
        $this->t_id = $value;
    }

    public function get_p_id()
    {
        return $this->p_id;
    }

    public function set_p_id($value)
    {
        $this->p_id = $value;
    }

    public function get_t_priority()
    {
        return $this->t_priority;
    }

    public function set_t_priority($value)
    {
        $this->t_priority = $value;
    }

    public function get_t_date()
    {
        return $this->t_date;
    }

    public function set_t_date($value)
    {
        $this->t_date = $value;
    }

    public function get_t_subject()
    {
        return $this->t_subject;
    }

    public function set_t_subject($value)
    {
        $this->t_subject = $value;
    }

    public function get_t_comments()
    {
        return $this->t_comments;
    }

    public function set_t_comments($value)
    {
        $this->t_comments = $value;
    }
}
